# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [2]:
import pandas as pd 
url_1="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df1=pd.read_csv(url_1)

url_2="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
df2=pd.read_csv(url_2)

url_3="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"
df3=pd.read_csv(url_3)

In [3]:
df1.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [4]:
def standardize(col_name):
  processed_name = col_name.lower().replace(' ', '_')
  if processed_name == 'st':
    return 'state'
  else:
    return processed_name

In [5]:
df1.columns=df1.columns.map(standardize)

In [6]:
df1.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [7]:
df1.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [8]:
df2.columns=df2.columns.map(standardize)

In [9]:
df2.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='object')

In [10]:
df2.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [11]:
df3.columns=df3.columns.map(standardize)

In [12]:
df3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='object')

In [13]:
df3.head()

,customer,state,customer_lifetime_value,education,gender,income,monthly_premium_auto,number_of_open_complaints,policy_type,total_claim_amount,vehicle_class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [14]:
insurance=pd.concat([df1, df2, df3], ignore_index=True,axis=0)

In [15]:
insurance.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [16]:
insurance.shape

(12074, 11)

In [17]:
insurance_copy=insurance.copy()

*Ya hemos combiando los tres dataframes , primero viendo que tienen las mismas columnas con los mismos nombres , poniendo ignore_index=True hacemo un nuevo índice para cada row.
Además, al tener el mimso nombre con la operación concat se ponen los valores debajo de su columna correspondiente. 
Si a concat, le añadimos sort=False , evitamos que se ordenen por orden alfabético.*

*Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [18]:
def clean_inconsistent_values(insurance):
    insurance_cleaned=insurance.copy()
    print("Cleaning Gender.")
    gender_map = {'Femal': 'F', 'female': 'F', 'Male': 'M'}
    insurance_cleaned['gender'] = insurance_cleaned['gender'].replace(gender_map)
    print("Cleaning State.")
    state_map = {"AZ": "Arizona", "Cali": "California", "WA": "Washington"}
    insurance_cleaned['state'] = insurance_cleaned['state'].replace(state_map)
    print("Cleaning Education.")
    education_map = {"Bachelors": "Bachelor"}
    insurance_cleaned['education'] = insurance_cleaned['education'].replace(education_map)
    print("Cleaning Customer Lifetime Value (removing '%').")
    # Use regex=False for simple literal replacement, potentially faster
    insurance_cleaned['customer_lifetime_value'] = insurance_cleaned['customer_lifetime_value'].astype(str).str.replace('%', '', regex=False)
    print("Cleaning Vehicle Class.")
    vehicle_map = {"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"}
    insurance_cleaned['vehicle_class'] = insurance_cleaned['vehicle_class'].replace(vehicle_map)

    print("Cleaning Process Finished ")
    return insurance_cleaned

In [19]:
insurance_cleaned=clean_inconsistent_values(insurance)

Cleaning Gender.
Cleaning State.
Cleaning Education.
Cleaning Customer Lifetime Value (removing '%').
Cleaning Vehicle Class.
Cleaning Process Finished

In [20]:
insurance_cleaned.head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,nan,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834

*Formatting data types*
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [2]:
#codigo
def corregir_tipos_datos(insurance_cleaned):
    print("Convirtiendo 'customer_lifetime_value' a numérico...")
    insurance_cleaned['customer_lifetime_value'] = pd.to_numeric(insurance_cleaned['customer_lifetime_value'], errors='coerce')
    print("Procesando y convirtiendo 'number_of_open_complaints'...")
    partes_quejas = insurance_cleaned['number_of_open_complaints'].str.split('/')
    numero_central_quejas = partes_quejas.str.get(1)
    quejas_numericas = pd.to_numeric(numero_central_quejas, errors='coerce')
    insurance_cleaned['number_of_open_complaints'] = quejas_numericas.astype("Int64")
    print("Corrección de tipos finalizada")
    return insurance_cleaned

In [3]:
corregir_tipos_datos(insurance_cleaned)

NameError: name 'insurance_cleaned' is not defined

*Valores nulos*

In [1]:
#codigo
# Identificar columnas con valores nulos

null_counts = insurance_cleaned.isnull().sum()
null_counts

NameError: name 'insurance_cleaned' is not defined

In [ ]:
#Elegir una estrategia
#Estrategia recomendada para este ejercicio:

#Para variables numéricas: rellenar con la media.
#Para variables categóricas (tipo object o category): rellenar con la moda

for col in df_cleaned.columns:
    if df_cleaned[col].isnull().sum() > 0:
        if df_cleaned[col].dtype == 'object':
            # Rellenar con la moda
            df_cleaned[col].fillna(df_cleaned[col].mode()[0], inplace=True)
        elif pd.api.types.is_integer_dtype(df_cleaned[col]):
            df_cleaned[col].fillna(round(df_cleaned[col].mean()), inplace=True)
        else:
            # Rellenar con la media
            df_cleaned[col].fillna(df_cleaned[col].mean(), inplace=True)

In [ ]:
df_cleaned.isnull().sum()

*Duplicados*

In [23]:
#codigo

duplicados= insurance_cleaned.duplicated() 
print(f"Número de filas duplicadas: {duplicados.sum()}")

Número de filas duplicadas: 2939

In [24]:
# Paso 2: Elegir una estrategia
# Elegimos mantener solo la primera ocurrencia de cada fila duplicada
# Esta es una estrategia común cuando se asume que los duplicados son registros repetidos por error

# Paso 3: Eliminar duplicados
insurance_cleaned = insurance_cleaned.drop_duplicates(keep='first')

In [25]:
# Paso 4: Resetear el índice tras eliminar duplicados
insurance_cleaned.reset_index(drop=True, inplace=True)

# Paso 5: Verificar que no queden duplicados
duplicados_post = insurance_cleaned.duplicated()
print(f"Número de filas duplicadas después de limpiar: {duplicados_post.sum()}")

# Paso 6: Guardar el DataFrame limpio a un nuevo archivo CSV
insurance_cleaned.to_csv('df_cleaned_sin_duplicados.csv', index=False)

Número de filas duplicadas después de limpiar: 0

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [5]:
# Your code goes here
import pandas as pd
url="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
df_plus=pd.read_csv(url)

In [6]:
df_plus.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [10]:
df_plus.head(1)

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.21696,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.8,Four-Door Car,Medsize,A,2

In [15]:
df_plus.dtypes

unnamed:_0                         int64
customer                          object
state                             object
customer_lifetime_value          float64
response                          object
coverage                          object
education                         object
effective_to_date                 object
employmentstatus                  object
gender                            object
income                             int64
location_code                     object
marital_status                    object
monthly_premium_auto               int64
months_since_last_claim          float64
months_since_policy_inception      int64
number_of_open_complaints        float64
number_of_policies                 int64
policy_type                       object
policy                            object
renew_offer_type                  object
sales_channel                     object
total_claim_amount               float64
vehicle_class                     object
vehicle_size                      object
vehicle_type                      object
month                              int64
dtype: object

In [ ]:
null_counts_plus = df_plus.isnull().sum()
null_counts_plus

In [ ]:
df_plus.duplicated()

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [16]:
# Crear una tabla resumen: ingresos totales por canal de ventas
pivot_revenue = pd.pivot_table(
    df_plus,
    values='total_claim_amount',
    index='sales_channel',
    aggfunc='sum'
)

# Redondear a 2 decimales
pivot_revenue = pivot_revenue.round(2)

In [18]:
print(pivot_revenue.sort_values(by='total_claim_amount', ascending=False))

               total_claim_amount
sales_channel
Agent                  1810226.82
Branch                 1301204.00
Call Center             926600.82
Web                     706600.04

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [ ]:
# Crear tabla resumen: valor de vida promedio por género y educación
pivot_lifetime_value = pd.pivot_table(
    df_plus,
    values='customer_lifetime_value',
    index='gender',
    columns='education',
    aggfunc='mean'
)

# Redondear a 2 decimales
pivot_lifetime_value = pivot_lifetime_value.round(2)

# Mostrar resultados
print("\nCustomer Lifetime Value promedio por género y nivel educativo:")
print(pivot_lifetime_value)

Customer Lifetime Value promedio por género y nivel educativo:
education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here